/* Problem Statement
>> Air Travel Is A Key Component Of Global Connectivity And Economic Development.

>> However, Understanding The Patterns Of Airport Usage, 
Including Passenger Flow And Route Popularity, Remains A Complex Challenge.

 >>The Project Seeks To Analyze Airport Data To Uncover Trends In Passenger Volume,
 Flight Frequency, And Seat Availability, And To Understand How Factors Such As City Population
 Impact Airport Operations. 
 
 >>The Goal Is To Provide Insights That Can Support 
 Airport Planning, Route Optimization, And Policy-Making.*/



-- 1. Analyze total passenger traffic per route and over time.

-- TOP 10 BUSIEST PASSENGER TRAFFIC ROUTE

SELECT  
		A1.CITY_NAME AS ORIGIN_CITY,
		A2.CITY_NAME AS DEST_CITY,
       SUM(F.PASSENGERS) AS TOTAL_PASSENGERS,
       F.YEAR,
       F.QUARTER
FROM FLIGHT F
LEFT JOIN AIRPORT A1 ON F.ORIGIN_AIRPORT_ID = A1.AIRPORT_ID
LEFT JOIN AIRPORT A2 ON F.DEST_AIRPORT_ID = A2.AIRPORT_ID
GROUP BY 1,2,4,5
ORDER BY  TOTAL_PASSENGERS DESC
LIMIT 10;




-- Least busiest routes


SELECT A1.CITY_NAME AS ORIGIN_CITY, A2.CITY_NAME AS DEST_CITY,
       SUM(F.PASSENGERS) AS TOTAL_PASSENGERS
FROM FLIGHT F
JOIN AIRPORT A1 ON F.ORIGIN_AIRPORT_ID = A1.AIRPORT_ID
JOIN AIRPORT A2 ON F.DEST_AIRPORT_ID = A2.AIRPORT_ID
WHERE A1.CITY_NAME <> A2.CITY_NAME 
GROUP BY A1.CITY_NAME, A2.CITY_NAME
HAVING SUM(F.PASSENGERS) > 0
ORDER BY TOTAL_PASSENGERS ASC
LIMIT 5;





-- 2. Determine average passengers per flight for various routes and airportS


-- FOR ROUTES

SELECT A1.CITY_NAME AS ORIGIN_CITY, A2.CITY_NAME AS DEST_CITY, 
       round(AVG(F.PASSENGERS)) AS AVG_PASSENGERS
FROM FLIGHT F
JOIN AIRPORT A1 ON F.ORIGIN_AIRPORT_ID = A1.AIRPORT_ID
JOIN AIRPORT A2 ON F.DEST_AIRPORT_ID = A2.AIRPORT_ID
GROUP BY 1,2
ORDER BY AVG_PASSENGERS DESC;




-- FOR AIRPORTS

WITH OUTGOING_PASSENGERS AS (
    SELECT ORIGIN_AIRPORT_ID, AVG(PASSENGERS) AS AVG_PASSENGERS
    FROM FLIGHT
    GROUP BY ORIGIN_AIRPORT_ID),
    
INCOMING_PASSENGERS AS (
    SELECT DEST_AIRPORT_ID, AVG(PASSENGERS) AS AVG_PASSENGERS
    FROM FLIGHT
    GROUP BY DEST_AIRPORT_ID),
    
ALL_AIRPORTS AS (
    SELECT DISTINCT ORIGIN_AIRPORT_ID AS AIRPORT_ID FROM FLIGHT
    UNION
    SELECT DISTINCT DEST_AIRPORT_ID AS AIRPORT_ID FROM FLIGHT
)
SELECT AA.AIRPORT_ID, A.CITY_NAME,
       round(OP.AVG_PASSENGERS + IP.AVG_PASSENGERS) AS TOTAL_AVG_PASSENGER
FROM ALL_AIRPORTS AA
LEFT JOIN AIRPORT A ON AA.AIRPORT_ID = A.AIRPORT_ID
LEFT JOIN OUTGOING_PASSENGERS OP ON AA.AIRPORT_ID = OP.ORIGIN_AIRPORT_ID
LEFT JOIN INCOMING_PASSENGERS IP ON AA.AIRPORT_ID = IP.DEST_AIRPORT_ID
WHERE    round(OP.AVG_PASSENGERS + IP.AVG_PASSENGERS)  IS NOT NULL
ORDER BY 3 DESC;




-- 3. Assess flight frequency and identify high-traffic corridors.


SELECT A1.CITY_NAME AS ORIGIN_CITY, A2.CITY_NAME AS DEST_CITY,
       COUNT(*) AS FLIGHT_FREQUENCY
FROM FLIGHT F
JOIN AIRPORT A1 ON F.ORIGIN_AIRPORT_ID = A1.AIRPORT_ID
JOIN AIRPORT A2 ON F.DEST_AIRPORT_ID = A2.AIRPORT_ID
GROUP BY 1,2
ORDER BY FLIGHT_FREQUENCY DESC
LIMIT 5;







-- 4. Compare passenger numbers across origin cities to identify top-performing airports.

SELECT A.CITY_NAME AS ORIGIN_CITY, 
		SUM(F.PASSENGERS) AS TOTAL_PASSENGERS,
		COUNT(F.AIRLINE_ID) AS FREQUENSY
FROM FLIGHT F JOIN AIRPORT A ON
F.ORIGIN_AIRPORT_ID = A.AIRPORT_ID
GROUP BY 1
ORDER BY 3 DESC  
LIMIT 10;






-- 5. Evaluate available seat capacity to understand seat utilization.


WITH SEATING_CAPACITY AS
(select AIRLINE_ID, max(PASSENGERS) as seat_capacity
from FLIGHT
group by 1
having max(PASSENGERS) > 0),

SEAT_UTI AS 
(SELECT SC.AIRLINE_ID, (F.PASSENGERS*100)/SC.SEAT_CAPACITY AS SEAT_UTILIZING
FROM SEATING_CAPACITY AS SC  JOIN FLIGHT F ON
SC.AIRLINE_ID = F.AIRLINE_ID)

SELECT SC.AIRLINE_ID , AI.CARRIER_NAME,
		ROUND(AVG(SC.SEAT_UTILIZING),2) AS AVG_S_UTILIZING
FROM SEAT_UTI  SC JOIN AIRLINE AI ON
SC.AIRLINE_ID = AI.AIRLINE_ID
GROUP BY 1,2
ORDER BY AVG_S_UTILIZING DESC
LIMIT 10;


-- OBJECTIVE 6: IDENTIFY POPULAR DESTINATION AIRPORTS BASED ON INBOUND PASSENGER COUNTS.



SELECT F.DEST_AIRPORT_ID ,A.CITY_NAME AS DEST_CITY , A.AIRPORT_CODE AS DEST_CODE, SUM(F.PASSENGERS) AS TOTAL_PASSENGERS
FROM FLIGHT F JOIN AIRPORT A ON
F.DEST_AIRPORT_ID = A.AIRPORT_ID
GROUP BY 1,2,3                                       
ORDER BY TOTAL_PASSENGERS DESC
LIMIT 10;









-- 7. EXAMINE THE RELATIONSHIP BETWEEN CITY POPULATION AND AIRPORT PASSENGER TRAFFIC.

WITH OUTGOING_PASSENGERS AS (
    SELECT ORIGIN_AIRPORT_ID, SUM(PASSENGERS) AS TOT_PASSENGERS
    FROM FLIGHT
    GROUP BY ORIGIN_AIRPORT_ID
),
INCOMING_PASSENGERS AS (
    SELECT DEST_AIRPORT_ID, SUM(PASSENGERS) AS TOT_PASSENGERS
    FROM FLIGHT
    GROUP BY DEST_AIRPORT_ID
),
ALL_AIRPORTS AS (
    SELECT DISTINCT AIRPORT_ID, CITY_NAME FROM AIRPORT
),
PASSENGER_TRAFFIC AS (
    SELECT SUBSTRING_INDEX(AA.CITY_NAME, ',', 1) AS CITY_NAME,
           OP.TOT_PASSENGERS + IP.TOT_PASSENGERS AS TOTAL_PASSENGER_TRAVELLING
    FROM AIRPORT AA
    LEFT JOIN OUTGOING_PASSENGERS OP ON AA.AIRPORT_ID = OP.ORIGIN_AIRPORT_ID
    LEFT JOIN INCOMING_PASSENGERS IP ON AA.AIRPORT_ID = IP.DEST_AIRPORT_ID
    WHERE OP.TOT_PASSENGERS + IP.TOT_PASSENGERS IS NOT NULL
),
CITY_LEVEL_TRAFFIC AS (
    SELECT CITY_NAME, 
    SUM(TOTAL_PASSENGER_TRAVELLING) AS TOTAL_PASSENGER_TRAVELLING
    FROM PASSENGER_TRAFFIC
    GROUP BY CITY_NAME
)

SELECT CP.CITY_NAME, 
		CP.POPULATION, 
		CLT.TOTAL_PASSENGER_TRAVELLING,
        ROUND((CLT.TOTAL_PASSENGER_TRAVELLING/CP.POPULATION),2) AS POP_PASSENGERS_RATIO
FROM CITY_LEVEL_TRAFFIC CLT
JOIN CITY_POP CP ON CLT.CITY_NAME = CP.CITY_NAME
WHERE CP.POPULATION IS NOT NULL AND CLT.TOTAL_PASSENGER_TRAVELLING IS NOT NULL
  AND CP.POPULATION <> 0 
ORDER BY POP_PASSENGERS_RATIO DESC;



-- 8. ASSESS THE IMPACT OF POPULATION SIZE ON FLIGHT FREQUENCY AND ROUTE CHOICES.

WITH ROUTE_FREQ AS
(SELECT  SUBSTRING_INDEX(A1.CITY_NAME,',',1)  AS ORIGIN_CITY,
		 SUBSTRING_INDEX(A2.CITY_NAME,',',1) AS DEST_CITY,
         COUNT(*) AS FLIGHT_FREQUENCY
FROM FLIGHT F 
JOIN AIRPORT A1 ON F.ORIGIN_AIRPORT_ID = A1.AIRPORT_ID
JOIN AIRPORT A2 ON F.DEST_AIRPORT_ID = A2.AIRPORT_ID
GROUP BY 1,2)

SELECT 	RF.ORIGIN_CITY, 
		C1.POPULATION AS ORIGIN_POP,
        RF.DEST_CITY,
        C2.POPULATION AS DEST_POP,
        RF.FLIGHT_FREQUENCY AS TOTAL_FLIGHT_FREQUENSY
FROM ROUTE_FREQ RF
JOIN CITY_POP C1 ON RF.ORIGIN_CITY = C1.CITY_NAME
JOIN CITY_POP C2 ON RF.DEST_CITY = C2.CITY_NAME
GROUP BY 1,2,3,4
ORDER BY 5 DESC;
        

