use flight_data;
select * from meta_data;

-- Making Relational Tables

CREATE TABLE AIRPORT(
AIRPORT_ID INT PRIMARY KEY,
AIRPORT_SEQUENCE_ID INT,
CITY_MARKET_ID INT ,
AIRPORT_CODE CHAR(10),
CITY_NAME VARCHAR(60),
STATE_ABR CHAR(8),
STATE_FIPS INT,
STATE_NM VARCHAR(60),
WAC INT);


-- INSERTING VALUES TO THE AIRPORT TABLE AND MAKE SURE ONE ROW PER AIRPORT .

INSERT INTO AIRPORT(AIRPORT_ID,
AIRPORT_SEQUENCE_ID,
CITY_MARKET_ID,
AIRPORT_CODE ,
CITY_NAME ,
STATE_ABR ,
STATE_FIPS,
STATE_NM ,
WAC)
SELECT DISTINCT ORIGIN_AIRPORT_ID, 
 ORIGIN_AIRPORT_SEQ_ID, ORIGIN_CITY_MARKET_ID, ORIGIN, ORIGIN_CITY_NAME,
 ORIGIN_STATE_ABR, ORIGIN_STATE_FIPS, 
 ORIGIN_STATE_NM, ORIGIN_WAC FROM META_DATA
 
 UNION

 SELECT DISTINCT 
 DEST_AIRPORT_ID, DEST_AIRPORT_SEQ_ID, DEST_CITY_MARKET_ID, 
 DEST, DEST_CITY_NAME, DEST_STATE_ABR, 
 DEST_STATE_FIPS, DEST_STATE_NM, DEST_WAC FROM META_DATA;
 
 SELECT * from Airport;
 
 CREATE TABLE AIRLINE(
 AIRLINE_ID INT PRIMARY KEY,
 CARRIER VARCHAR(100),
 CARRIER_NAME VARCHAR(100),
 CARRIER_ENTITY VARCHAR(8)
 );
 
 -- INSERTING DATA IN TO AIRLINE TABLE
 
 INSERT IGNORE INTO AIRLINE(AIRLINE_ID,
 CARRIER ,
 CARRIER_NAME,
 CARRIER_ENTITY)
 SELECT DISTINCT AIRLINE_ID,UNIQUE_CARRIER,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY
 FROM META_DATA;
 
 SELECT * FROM  AIRLINE;

CREATE TABLE FLIGHT(
AIRLINE_ID INT,
ORIGIN_AIRPORT_ID INT,
DEST_AIRPORT_ID INT,
PASSENGERS INT,
FREIGHT INT,
MAIL INT,
DISTANCE INT,
YEAR INT,
QUARTER INT,
MONTH INT,
DISTANCE_GROUP int,
CLASS CHAR(1),
FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE(AIRLINE_ID),
FOREIGN KEY (ORIGIN_AIRPORT_ID) REFERENCES AIRPORT(AIRPORT_ID),
FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES AIRPORT(AIRPORT_ID));

INSERT INTO FLIGHT(AIRLINE_ID,
ORIGIN_AIRPORT_ID ,
DEST_AIRPORT_ID ,
PASSENGERS ,
FREIGHT ,
MAIL ,
DISTANCE,
YEAR ,
QUARTER,
MONTH,
DISTANCE_GROUP,
CLASS)
SELECT  AIRLINE_ID,
ORIGIN_AIRPORT_ID ,
DEST_AIRPORT_ID ,
PASSENGERS ,
FREIGHT ,
MAIL ,
DISTANCE,
YEAR ,
QUARTER,
MONTH,
DISTANCE_GROUP ,
CLASS
FROM META_DATA;

SELECT * FROM FLIGHT;


CREATE TABLE CITY(
CITY_NAME VARCHAR(60),
STATE_ABR CHAR(8),
STATE_NM VARCHAR(60)
);

INSERT INTO CITY(CITY_NAME,STATE_ABR,STATE_NM)
SELECT CITY_NAME,STATE_ABR,STATE_NM
FROM AIRPORT;

SELECT * FROM CITY;
SELECT * FROM META_DATA;

SELECT COUNT(*) FROM META_DATA WHERE ORIGIN = 'SEA' AND DEST = 'LAX';